[package]
name = "gossip-impl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gossip = { git = "https://github.com/bmstu-iu8-2021-project/gossip" }
env_logger = "^0.9.0"
